/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIMedicine;

import java.awt.Color;
import java.io.*;

/**
 *
 * @author Gamaliel
 */
public class MedicineMachine extends javax.swing.JFrame {

    MedicineData data = new MedicineData();
    addProgram addP = new addProgram();
    MedicineSimulator simulate = new MedicineSimulator();
    errorCheck check = new errorCheck();
    
    String filename = "medicine.dat";
    
    public MedicineMachine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        regAddBtn = new javax.swing.JButton();
        regEditBtn = new javax.swing.JButton();
        regDeleteBtn = new javax.swing.JButton();
        regCancelBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        regUsernameFld = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        regPasswordFld = new javax.swing.JPasswordField();
        regUserLogInBtn = new javax.swing.JButton();
        regUserClearBtn = new javax.swing.JButton();
        regUserLogOutBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        regMedCodeFld = new javax.swing.JTextField();
        regGenericFld = new javax.swing.JTextField();
        regBrandFld = new javax.swing.JTextField();
        regPriceFld = new javax.swing.JTextField();
        regQtyFld = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        regTypeBox = new javax.swing.JComboBox();
        regTypeFld = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        regExpBox = new javax.swing.JComboBox();
        regDayFld = new javax.swing.JTextField();
        regYearFld = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        messageStatus = new javax.swing.JLabel();
        regOkBtn = new javax.swing.JButton();
        regSaveBtn = new javax.swing.JButton();
        regClearBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        regDisplayFld = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Medicine Registrar");
        setBounds(new java.awt.Rectangle(260, 10, 0, 0));
        setPreferredSize(new java.awt.Dimension(700, 640));
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Control Panel", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 10), new java.awt.Color(0, 51, 51))); // NOI18N

        regAddBtn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        regAddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON PNG/addNew.png"))); // NOI18N
        regAddBtn.setText("ADD");
        regAddBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        regAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regAddBtnActionPerformed(evt);
            }
        });

        regEditBtn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        regEditBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON PNG/editMed.png"))); // NOI18N
        regEditBtn.setText("EDIT");
        regEditBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        regEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regEditBtnActionPerformed(evt);
            }
        });

        regDeleteBtn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        regDeleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON PNG/deleteMed.png"))); // NOI18N
        regDeleteBtn.setText("DELETE");
        regDeleteBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        regDeleteBtn.setMargin(new java.awt.Insets(2, 0, 2, 0));
        regDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regDeleteBtnActionPerformed(evt);
            }
        });

        regCancelBtn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        regCancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON PNG/cancelMed.png"))); // NOI18N
        regCancelBtn.setText("CANCEL");
        regCancelBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        regCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(regAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regCancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(regAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(regEditBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Log-in Account", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 10), new java.awt.Color(0, 51, 51))); // NOI18N
        jPanel4.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel2.setText("Password");

        regUserLogInBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 9)); // NOI18N
        regUserLogInBtn.setText("LOG-IN");
        regUserLogInBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        regUserLogInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regUserLogInBtnActionPerformed(evt);
            }
        });

        regUserClearBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 9)); // NOI18N
        regUserClearBtn.setText("CLEAR");
        regUserClearBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        regUserLogOutBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 9)); // NOI18N
        regUserLogOutBtn.setText("LOG-OUT");
        regUserLogOutBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        regUserLogOutBtn.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(regPasswordFld, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(regUsernameFld))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(regUserLogInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regUserClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regUserLogOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(regUsernameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regPasswordFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regUserLogInBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regUserClearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regUserLogOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Data", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 10), new java.awt.Color(0, 51, 51))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 10)); // NOI18N
        jLabel3.setText("Medicine Code");

        jLabel4.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 10)); // NOI18N
        jLabel4.setText("Generic");

        jLabel5.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 10)); // NOI18N
        jLabel5.setText("Price");

        jLabel6.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 10)); // NOI18N
        jLabel6.setText("Brand");

        jLabel7.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 10)); // NOI18N
        jLabel7.setText("Quantity");

        regMedCodeFld.setEnabled(false);
        regMedCodeFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regMedCodeFldActionPerformed(evt);
            }
        });

        regGenericFld.setEnabled(false);

        regBrandFld.setEnabled(false);

        regPriceFld.setEnabled(false);
        regPriceFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regPriceFldActionPerformed(evt);
            }
        });

        regQtyFld.setEnabled(false);
        regQtyFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regQtyFldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 10)); // NOI18N
        jLabel8.setText("Type");

        regTypeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C" }));
        regTypeBox.setEnabled(false);
        regTypeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regTypeBoxActionPerformed(evt);
            }
        });

        regTypeFld.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 10)); // NOI18N
        regTypeFld.setText(" TABLET");
        regTypeFld.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 10)); // NOI18N
        jLabel9.setText("Expiry");

        regExpBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        regExpBox.setEnabled(false);

        regDayFld.setText("DD");
        regDayFld.setEnabled(false);

        regYearFld.setText("YY");
        regYearFld.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(regExpBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(regDayFld)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(regYearFld))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(46, 46, 46))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(regGenericFld, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(regMedCodeFld, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(regBrandFld, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(regPriceFld, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(regQtyFld, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(regTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(regTypeFld, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(regMedCodeFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(regGenericFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regBrandFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(regTypeFld))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(regExpBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regDayFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regYearFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regQtyFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(regPriceFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        messageStatus.setFont(new java.awt.Font("Century Gothic", 2, 10)); // NOI18N
        messageStatus.setForeground(new java.awt.Color(204, 0, 0));
        messageStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        regOkBtn.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        regOkBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON PNG/ok.png"))); // NOI18N
        regOkBtn.setText("OK");
        regOkBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        regOkBtn.setEnabled(false);
        regOkBtn.setMargin(new java.awt.Insets(2, 0, 2, 0));
        regOkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regOkBtnActionPerformed(evt);
            }
        });

        regSaveBtn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        regSaveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON PNG/saveMed.png"))); // NOI18N
        regSaveBtn.setText("SAVE");
        regSaveBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        regSaveBtn.setEnabled(false);
        regSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regSaveBtnActionPerformed(evt);
            }
        });

        regClearBtn.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        regClearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON PNG/clearMed.png"))); // NOI18N
        regClearBtn.setText("CLEAR");
        regClearBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        regClearBtn.setEnabled(false);
        regClearBtn.setMargin(new java.awt.Insets(2, 0, 2, 0));
        regClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regClearBtnActionPerformed(evt);
            }
        });

        regDisplayFld.setColumns(20);
        regDisplayFld.setRows(5);
        jScrollPane2.setViewportView(regDisplayFld);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(regOkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(regSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(regClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(174, 174, 174))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(regClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regOkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Registry", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Records", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Purchase", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regMedCodeFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regMedCodeFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regMedCodeFldActionPerformed

    private void regQtyFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regQtyFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regQtyFldActionPerformed

    private void regUserLogInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regUserLogInBtnActionPerformed
        String username = regUsernameFld.getText();
        
        if(username.equals("admin") ){
            
        }
    }//GEN-LAST:event_regUserLogInBtnActionPerformed

    private void regAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regAddBtnActionPerformed
        
        regDeleteBtn.setEnabled(false);
        regEditBtn.setEnabled(false);
        regMedCodeFld.setEnabled(true);
        regGenericFld.setEnabled(true);
        regBrandFld.setEnabled(true);
        regTypeBox.setEnabled(true);
        regTypeFld.setEnabled(true);
        regExpBox.setEnabled(true);
        regDayFld.setEnabled(true);
        regYearFld.setEnabled(true);
        regPriceFld.setEnabled(true);
        regQtyFld.setEnabled(true);      
        regClearBtn.setEnabled(true);
        regOkBtn.setEnabled(false);
        regSaveBtn.setEnabled(true);
        data.action(0);
    }//GEN-LAST:event_regAddBtnActionPerformed

    private void regOkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regOkBtnActionPerformed
       
        /* Registry Status legend:
         * 1 = EDIT
         * 2 = DELETE
        */
        messageStatus.setText("");
        if(data.getRegistryStatus() == 1){          // Code start for ADD
        try{
             data.open(filename);
            if(regMedCodeFld.getText().isEmpty()){
                check.setStatusCode(101);
                check.setControl(false);
                messageStatus.setForeground(Color.red);
                messageStatus.setText(messageStatus.getText() + " " + check.redStatusCode(check.getStatusCode()));
            }
            
            int medCode;
            medCode = Integer.parseInt(regMedCodeFld.getText());
                int find = data.find(medCode);
                if(find == -1 ){
                    messageStatus.setForeground(Color.red);
                    String status = check.redStatusCode(202);
                    messageStatus.setText("Error: " + status);
                    check.setControl(false);
                }
                else{
                    data.read(find);
                   
          
                    check.setControl(true);
                }
        }catch(Exception e){
            
        }
        }// Code end for EDIT
    }//GEN-LAST:event_regOkBtnActionPerformed

    private void regClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regClearBtnActionPerformed
        messageStatus.setText(null);
        regMedCodeFld.setText(null);
        regGenericFld.setText(null);
        regBrandFld.setText(null);
        regTypeBox.setSelectedIndex(0);
        regExpBox.setSelectedIndex(0);
        regDayFld.setText("DD");
        regYearFld.setText("YY");
        regPriceFld.setText(null);
        regQtyFld.setText(null);
        regDisplayFld.setText(null);
    }//GEN-LAST:event_regClearBtnActionPerformed

    private void regPriceFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regPriceFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regPriceFldActionPerformed

    private void regCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regCancelBtnActionPerformed
        regClearBtn.doClick();
        regAddBtn.setEnabled(true);
        regEditBtn.setEnabled(true);
        regDeleteBtn.setEnabled(true);
        regMedCodeFld.setEnabled(false);
        regGenericFld.setEnabled(false);
        regBrandFld.setEnabled(false);
        regPriceFld.setEnabled(false);
        regQtyFld.setEnabled(false);      
        regClearBtn.setEnabled(false);
        regOkBtn.setEnabled(false);
        regDisplayFld.setEnabled(false);
        regSaveBtn.setEnabled(false);
        regTypeBox.setEnabled(false);
        regTypeFld.setEnabled(false);
        regExpBox.setEnabled(false);
        regDayFld.setEnabled(false);
        regYearFld.setEnabled(false);
        data.action(9);
    }//GEN-LAST:event_regCancelBtnActionPerformed

    private void regEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regEditBtnActionPerformed
        regDeleteBtn.setEnabled(false);
        regAddBtn.setEnabled(false);
        regMedCodeFld.setEnabled(true);
        regOkBtn.setEnabled(true);
        regClearBtn.setEnabled(true);
        data.action(1);
    }//GEN-LAST:event_regEditBtnActionPerformed

    private void regDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regDeleteBtnActionPerformed
        regEditBtn.setEnabled(false);
        regAddBtn.setEnabled(false);
        regMedCodeFld.setEnabled(true);
        regOkBtn.setEnabled(true);
        regClearBtn.setEnabled(true);
        data.action(2);
    }//GEN-LAST:event_regDeleteBtnActionPerformed

    private void regSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regSaveBtnActionPerformed

        /* Registry Status legend:
         * 0 = ADD
         * 1 = EDIT
         * 2 = DELETE
        */
        if(data.getRegistryStatus() == 0){  // code start for ADD
            emptySlots();                   // check if field is empty
        
        } // Code end for ADD
        
        
        
    }//GEN-LAST:event_regSaveBtnActionPerformed

    private void regTypeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regTypeBoxActionPerformed
        if (regTypeBox.getSelectedIndex() == 0) {
            regTypeFld.setText("TABLET");
        } else if (regTypeBox.getSelectedIndex() == 1) {
            regTypeFld.setText("CAPSULE");
        } else if (regTypeBox.getSelectedIndex() == 2) {
            regTypeFld.setText("SYRUP");
        }

    }//GEN-LAST:event_regTypeBoxActionPerformed

    private void emptySlots(){
        
         messageStatus.setText("");
        
        if((regMedCodeFld.getText()).isEmpty()){
            check.setStatusCode(101);
            check.setControl(false);
            messageStatus.setForeground(Color.red);            
            messageStatus.setText(messageStatus.getText()+" "+check.redStatusCode(check.getStatusCode()));
        }
        if((regGenericFld.getText()).isEmpty()){
            check.setStatusCode(102);
            check.setControl(false);
            messageStatus.setForeground(Color.red);
            messageStatus.setText(messageStatus.getText()+" "+check.redStatusCode(check.getStatusCode()));
        }
        if((regBrandFld.getText()).isEmpty()){
            check.setStatusCode(103);
            check.setControl(false);
            messageStatus.setForeground(Color.red);
            messageStatus.setText(messageStatus.getText()+" "+check.redStatusCode(check.getStatusCode()));
        }
        if((regPriceFld.getText()).isEmpty()){
            check.setStatusCode(104);
            check.setControl(false);
            messageStatus.setForeground(Color.red);
            messageStatus.setText(messageStatus.getText()+" "+check.redStatusCode(check.getStatusCode()));
        }
        if((regQtyFld.getText()).isEmpty()){
            check.setStatusCode(105);
            check.setControl(false);
            messageStatus.setForeground(Color.red);
            messageStatus.setText(messageStatus.getText()+" "+check.redStatusCode(check.getStatusCode()));            
        }
        if((regQtyFld.getText()).isEmpty()){
            check.setStatusCode(106);
            check.setControl(false);
            messageStatus.setForeground(Color.red);
            messageStatus.setText(messageStatus.getText()+" "+check.redStatusCode(check.getStatusCode()));            
        }
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicineMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicineMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicineMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicineMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicineMachine().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel messageStatus;
    private javax.swing.JButton regAddBtn;
    private javax.swing.JTextField regBrandFld;
    private javax.swing.JButton regCancelBtn;
    private javax.swing.JButton regClearBtn;
    private javax.swing.JTextField regDayFld;
    private javax.swing.JButton regDeleteBtn;
    private javax.swing.JTextArea regDisplayFld;
    private javax.swing.JButton regEditBtn;
    private javax.swing.JComboBox regExpBox;
    private javax.swing.JTextField regGenericFld;
    private javax.swing.JTextField regMedCodeFld;
    private javax.swing.JButton regOkBtn;
    private javax.swing.JPasswordField regPasswordFld;
    private javax.swing.JTextField regPriceFld;
    private javax.swing.JTextField regQtyFld;
    private javax.swing.JButton regSaveBtn;
    private javax.swing.JComboBox regTypeBox;
    private javax.swing.JLabel regTypeFld;
    private javax.swing.JButton regUserClearBtn;
    private javax.swing.JButton regUserLogInBtn;
    private javax.swing.JButton regUserLogOutBtn;
    private javax.swing.JTextField regUsernameFld;
    private javax.swing.JTextField regYearFld;
    // End of variables declaration//GEN-END:variables
}
